### ISSUE TITLE
CUDA out of memory on 8xA100 GPUs

### ISSUE THREAD

**Issue by l3utterfly** [imoneoi/openchat#34]
Tried running the sample training script on 8xA100 GPUs. Used the sharegpt_v3.2 dataset recommended in your ReadMe.

I got this error: `CUDA out of memory. Tried to allocate 688.00 MiB (GPU 1; 39.39 GiB total capacity; 37.95 GiB already allocated; 633.12 MiB free; 38.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

What setting did you use to train? I tried setting `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512` as a test, still ran into the same out of memory error.

**Comment by imoneoi** [comment]
Are you using A100 80GB or 40GB?

**Comment by l3utterfly** [comment]
80G, you can see in the error message, 40G is allocated, 40G is reserved

**Comment by l3utterfly** [comment]
oh, nvm, yes I'm using 40GB one. I reduced the batch size per gpu and it works

**Comment by l3utterfly** [comment]
btw, I just started a training run, the estimated time is about 36 hours. (Though I'm barely five minutes into the run, so it might not have warmed up yet).

Will the VRAM size affect training speed? You mentioned you can train this in under 1 hour using 8xA100?

**Comment by imoneoi** [comment]
Which dataset are you using?

**Comment by imoneoi** [comment]
With 8xA100 80GB + OpenChat 3.2 dataset, we can finish training in 10 hours

**Comment by l3utterfly** [comment]
https://huggingface.co/datasets/openchat/openchat_sharegpt_v3: `sharegpt_v3.2.train.parquet`

Estimated 25 hours training time right now.

**Comment by imoneoi** [comment]
I finished training on this dataset in 10hrs.Try to tune hyperparameters such as batch size, ZeRO stage 2/3, CPU offload, etc.?

**Comment by imoneoi** [comment]
A100 40GB may be slower because of smaller batch / CPU offloading etc.

**Comment by chunhualiu** [comment]
> A100 40GB may be slower because of smaller batch / CPU offloading etc.

I am using 8x NVIDIA A100-PCIE-40GB, still got 'torch.cuda.OutOfMemoryError'
I even set batch_size_per_gpu to 1.
And PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
Below is the command I am using, any idea what's wrong:

```
deepspeed --num_gpus=$NUM_GPUS --module ochat.training_deepspeed.train \
    --model_type openchat_v3.2 \
    --model_path /data/LLaMA2_13B_with_EOT_token \
    --data_path /data/openchat_sharegpt_v3/openchat_v3.2_super \
    --save_path /data/output \
    --epochs 5 \
    --batch_size_per_gpu 1 \
    --deepspeed \
    --deepspeed_config ochat/training_deepspeed/deepspeed_config.json
```

The error:

```
Traceback (most recent call last):
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/openchat/ochat/training_deepspeed/train.py", line 342, in <module>
    train()
  File "/home/test/openchat/ochat/training_deepspeed/train.py", line 247, in train
    model_engine, optimizer = create_model(args)
  File "/home/test/openchat/ochat/training_deepspeed/train.py", line 162, in create_model
    model_engine, optimizer, _, _ = deepspeed.initialize(args=args,
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 303, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1213, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1467, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 516, in __init__
    self.initialize_optimizer_states()
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 651, in initialize_optimizer_states
    self.optimizer.step()
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/torch/optim/optimizer.py",line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/torch/optim/optimizer.py",line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/torch/optim/adamw.py", line 160, in step
    self._init_group(
  File "/home/test/miniconda3/envs/openchat/lib/python3.10/site-packages/torch/optim/adamw.py", line 114, in _init_group
    state["exp_avg"] = torch.zeros_like(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.06 GiB (GPU 7; 39.43 GiB total capacity; 36.37 GiB already allocated; 1.98 GiB free; 36.37 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by Altenrion** [comment]
@chunhualiu Did you solve your case?

**Comment by Hi-Angel** [comment]
> oh, nvm, yes I'm using 40GB one. I reduced the batch size per gpu and it works

@l3utterfly could you please clarify how exactly did you work around this problem? Did you change some env. variable? What did you set it to? FYI, [it is a popular problem](https://github.com/imoneoi/openchat/issues/107), so there's quite a number of users looking for a workaround of some sort, and we don't even do training, just trying to launch the server to use the pre-trained data.

**Comment by Pjstolas** [comment]
Seams that people lose faith on the solution and gives up. I'm running the same problem with a 3080ti

**Comment by Hi-Angel** [comment]
IIUC the project is inactive.

For those who just want to chat with an AI running locally I recommend these days cross-platform `lm-studio`.
